# Generated by Django 3.1.6 on 2023-09-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(choices=[(17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25')])),
                ('course', models.CharField(max_length=50)),
                ('passed_out_year', models.CharField(max_length=4)),
                ('insitute_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_No', models.CharField(max_length=10)),
            ],
        ),
    ]
